title: Profile
author: Khawahish
email: khawahisharora20@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 i donot feel like thinking what to write so i am just writing some rubbish stuff out here.
# social links
i will not share 

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
